-- =============================================================================
-- Migration: 20260905000000_fase8_publisher_profile_history_and_semantic_diff.sql
-- Descrição: Tabelas de histórico e notificações de auditoria de perfil de publicador,
--            RPC de diff semântico inteligente (eliminando falsos positivos 'NÃO VERDADE'),
--            fallback rigoroso 'legado' e blindagem de alteração de autor estritamente para admin.
-- =============================================================================

-- 1. Tabela de histórico de alterações de perfil
CREATE TABLE IF NOT EXISTS public.publisher_profile_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id text NOT NULL,
    publisher_name text,
    prev_data jsonb,
    new_data jsonb,
    changed_fields text[] NOT NULL DEFAULT '{}',
    source text NOT NULL DEFAULT 'web_form',
    author_label text NOT NULL DEFAULT 'legado',
    author_id text,
    token text,
    ip_address text,
    user_agent text,
    changed_at timestamp with time zone NOT NULL DEFAULT now()
);

-- 2. Tabela de notificações de alterações para o painel admin
CREATE TABLE IF NOT EXISTS public.publisher_profile_change_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id bigint REFERENCES public.publisher_profile_history(id) ON DELETE CASCADE,
    publisher_id text NOT NULL,
    publisher_name text,
    severity text NOT NULL DEFAULT 'info',
    summary text NOT NULL,
    changed_fields text[] NOT NULL DEFAULT '{}',
    affected_part_ids uuid[] NOT NULL DEFAULT '{}',
    affected_part_count integer NOT NULL DEFAULT 0,
    source text NOT NULL DEFAULT 'web_form',
    author_label text NOT NULL DEFAULT 'legado',
    dismissed_at timestamp with time zone,
    dismissed_by text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Índices de performance
CREATE INDEX IF NOT EXISTS idx_pub_prof_hist_pub_id ON public.publisher_profile_history(publisher_id);
CREATE INDEX IF NOT EXISTS idx_pub_prof_hist_changed_at ON public.publisher_profile_history(changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_pub_prof_notif_dismissed ON public.publisher_profile_change_notifications(dismissed_at) WHERE dismissed_at IS NULL;

-- RLS
ALTER TABLE public.publisher_profile_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publisher_profile_change_notifications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'publisher_profile_history' AND policyname = 'publisher_profile_history_admin_read'
    ) THEN
        CREATE POLICY "publisher_profile_history_admin_read" ON public.publisher_profile_history
            FOR SELECT USING (public.is_admin());
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'publisher_profile_change_notifications' AND policyname = 'publisher_profile_change_notifications_admin_read'
    ) THEN
        CREATE POLICY "publisher_profile_change_notifications_admin_read" ON public.publisher_profile_change_notifications
            FOR SELECT USING (public.is_admin());
    END IF;
END $$;

-- 3. Dropar sobrecarga legada permissiva que aceitava tokens na edição de autor
DROP FUNCTION IF EXISTS public.update_publisher_profile_history_author(bigint, text, text);

-- 4. RPC: record_publisher_profile_change (Diff semântico rigoroso e fallback 'legado')
CREATE OR REPLACE FUNCTION public.record_publisher_profile_change(
    p_publisher_id text, 
    p_prev_data jsonb, 
    p_new_data jsonb, 
    p_source text, 
    p_author_label text, 
    p_author_id text DEFAULT NULL::text, 
    p_token text DEFAULT NULL::text, 
    p_ip text DEFAULT NULL::text, 
    p_ua text DEFAULT NULL::text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    v_publisher_name TEXT;
    v_changed_fields TEXT[] := '{}';
    v_history_id BIGINT;
    v_severity TEXT;
    v_summary TEXT;
    v_critical_fields TEXT[] := ARRAY['privileges','privilegesBySection','gender','restrictions','status','active','isNotQualified','isIndefinitelyPaused'];
    v_meta JSONB;
    v_effective_author TEXT;
BEGIN
    v_publisher_name := COALESCE(p_new_data->>'name', p_prev_data->>'name', p_publisher_id);
    v_effective_author := COALESCE(NULLIF(TRIM(p_author_label), ''), 'legado');

    -- Diff semântico rigoroso: evita falsos positivos de null vs false, null vs "", null vs []
    WITH all_keys AS (
        SELECT DISTINCT k
        FROM (
            SELECT key AS k FROM jsonb_each(COALESCE(p_new_data, '{}'::jsonb))
            UNION
            SELECT key AS k FROM jsonb_each(COALESCE(p_prev_data, '{}'::jsonb))
        ) keys
        WHERE k NOT IN ('availability','availabilityMeta','profileMeta','updatedAt','updatedBy','id')
    )
    SELECT COALESCE(array_agg(DISTINCT k ORDER BY k), '{}')
      INTO v_changed_fields
      FROM all_keys
     WHERE (
        CASE 
            WHEN k IN ('isNotQualified', 'requestedNoParticipation', 'isIndefinitelyPaused', 'isHelperOnly', 'canPairWithNonParent') THEN
                COALESCE((p_prev_data->>k)::boolean, false) IS DISTINCT FROM COALESCE((p_new_data->>k)::boolean, false)
            WHEN k IN ('isServing', 'isBaptized', 'active') THEN
                COALESCE((p_prev_data->>k)::boolean, true) IS DISTINCT FROM COALESCE((p_new_data->>k)::boolean, true)
            WHEN k IN ('phone', 'contact_phone') THEN
                regexp_replace(COALESCE(p_prev_data->>k, ''), '\\D', '', 'g') IS DISTINCT FROM regexp_replace(COALESCE(p_new_data->>k, ''), '\\D', '', 'g')
            WHEN k IN ('notQualifiedReason', 'noParticipationReason', 'indefinitePauseReason', 'email', 'spouseId', 'name', 'gender', 'ageGroup', 'condition', 'funcao', 'address', 'status') THEN
                NULLIF(TRIM(COALESCE(p_prev_data->>k, '')), '') IS DISTINCT FROM NULLIF(TRIM(COALESCE(p_new_data->>k, '')), '')
            WHEN k IN ('parentIds', 'aliases', 'syntheticProfiles') THEN
                COALESCE(p_prev_data->k, '[]'::jsonb) IS DISTINCT FROM COALESCE(p_new_data->k, '[]'::jsonb)
            WHEN k = 'privileges' THEN
                EXISTS (
                    SELECT 1 FROM unnest(ARRAY['canPreside', 'canGiveTalks', 'canGiveStudentTalks', 'canPray', 'canReadCBS', 'canConductCBS']) AS sub_k
                    WHERE COALESCE((p_prev_data->'privileges'->>sub_k)::boolean, false) IS DISTINCT FROM COALESCE((p_new_data->'privileges'->>sub_k)::boolean, false)
                )
            WHEN k = 'privilegesBySection' THEN
                EXISTS (
                    SELECT 1 FROM unnest(ARRAY['canParticipateInTreasures', 'canParticipateInMinistry', 'canParticipateInLife']) AS sub_k
                    WHERE COALESCE((p_prev_data->'privilegesBySection'->>sub_k)::boolean, false) IS DISTINCT FROM COALESCE((p_new_data->'privilegesBySection'->>sub_k)::boolean, false)
                )
            ELSE
                COALESCE(p_prev_data->k, 'null'::jsonb) IS DISTINCT FROM COALESCE(p_new_data->k, 'null'::jsonb)
                AND NOT (
                    (p_prev_data->k IS NULL OR p_prev_data->k = 'null'::jsonb OR p_prev_data->k = '""'::jsonb OR p_prev_data->k = 'false'::jsonb OR p_prev_data->k = '[]'::jsonb)
                    AND
                    (p_new_data->k IS NULL OR p_new_data->k = 'null'::jsonb OR p_new_data->k = '""'::jsonb OR p_new_data->k = 'false'::jsonb OR p_new_data->k = '[]'::jsonb)
                )
        END
     ) = true;

    IF array_length(v_changed_fields, 1) IS NULL OR array_length(v_changed_fields, 1) = 0 THEN
        RETURN jsonb_build_object('success', true, 'no_changes', true);
    END IF;

    -- severity: warning se algum campo crítico, senão info
    IF v_changed_fields && v_critical_fields THEN
        v_severity := 'warning';
    ELSE
        v_severity := 'info';
    END IF;

    v_summary := format('Perfil de %s atualizado por %s (%s campo(s)).',
        v_publisher_name, v_effective_author, array_length(v_changed_fields, 1));

    INSERT INTO public.publisher_profile_history
        (publisher_id, publisher_name, prev_data, new_data, changed_fields,
         source, author_label, author_id, token, ip_address, user_agent)
    VALUES (p_publisher_id, v_publisher_name, p_prev_data, p_new_data, v_changed_fields,
        p_source, v_effective_author, p_author_id,
        CASE WHEN p_token IS NOT NULL THEN substring(p_token, 1, 8) || '…' ELSE NULL END,
        p_ip, p_ua)
    RETURNING id INTO v_history_id;

    INSERT INTO public.publisher_profile_change_notifications
        (history_id, publisher_id, publisher_name, severity, summary, changed_fields,
         affected_part_ids, affected_part_count, source, author_label)
    VALUES (v_history_id, p_publisher_id, v_publisher_name, v_severity, v_summary, v_changed_fields,
        '{}'::uuid[], 0, p_source, v_effective_author);

    -- Stamp metadata em publishers.data.profileMeta (sem alterar restante)
    v_meta := jsonb_build_object(
        'updatedAt', to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'updatedBy', v_effective_author,
        'updatedById', p_author_id,
        'source', p_source,
        'changedFields', to_jsonb(v_changed_fields)
    );
    UPDATE public.publishers
       SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{profileMeta}', v_meta, true)
     WHERE id = p_publisher_id;

    RETURN jsonb_build_object('success', true, 'historyId', v_history_id,
        'changedFields', to_jsonb(v_changed_fields), 'severity', v_severity);
END;
$function$;

-- 5. RPC: get_publisher_profile_history_for_form
CREATE OR REPLACE FUNCTION public.get_publisher_profile_history_for_form(
    p_token text DEFAULT NULL::text, 
    p_publisher_id text DEFAULT NULL::text
)
RETURNS TABLE(
    id bigint, 
    publisher_id text, 
    publisher_name text, 
    changed_fields text[], 
    prev_data jsonb, 
    new_data jsonb, 
    source text, 
    author_label text, 
    author_id text, 
    changed_at timestamp with time zone
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_valid boolean := false;
BEGIN
  IF p_token IS NOT NULL AND p_token <> '' THEN
    SELECT EXISTS (
      SELECT 1 FROM publisher_form_tokens
      WHERE token = p_token
        AND revoked_at IS NULL
        AND (expires_at IS NULL OR expires_at > now())
    ) INTO v_valid;
  END IF;

  IF NOT v_valid AND NOT public.is_admin() THEN
    IF auth.uid() IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
      ) INTO v_valid;
    END IF;
  END IF;

  IF NOT v_valid AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'unauthorized' USING ERRCODE = '28000';
  END IF;

  RETURN QUERY
  SELECT 
    h.id,
    h.publisher_id,
    h.publisher_name,
    h.changed_fields,
    h.prev_data,
    h.new_data,
    h.source,
    h.author_label,
    h.author_id,
    h.changed_at
  FROM publisher_profile_history h
  WHERE (p_publisher_id IS NULL OR h.publisher_id = p_publisher_id)
  ORDER BY h.changed_at DESC
  LIMIT 500;
END;
$function$;

-- 6. RPC: dismiss_publisher_profile_notification
CREATE OR REPLACE FUNCTION public.dismiss_publisher_profile_notification(p_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE 
    v_email TEXT;
BEGIN
    IF auth.uid() IS NULL OR NOT public.is_admin() THEN
        RETURN jsonb_build_object('success', false, 'error', 'not_authorized');
    END IF;
    SELECT email INTO v_email FROM profiles WHERE id = auth.uid();
    UPDATE public.publisher_profile_change_notifications
       SET dismissed_at = COALESCE(dismissed_at, now()),
           dismissed_by = COALESCE(dismissed_by, v_email)
     WHERE id = p_id;
    RETURN jsonb_build_object('success', true);
END;
$function$;

-- 7. RPC: update_publisher_profile_history_author (ESTRITAMENTE ADMIN)
CREATE OR REPLACE FUNCTION public.update_publisher_profile_history_author(
    p_history_id bigint DEFAULT NULL::bigint, 
    p_new_author_label text DEFAULT NULL::text, 
    p_publisher_id text DEFAULT NULL::text, 
    p_token text DEFAULT NULL::text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    v_valid BOOLEAN := false;
    v_publisher_id TEXT := p_publisher_id;
    v_cleaned_author TEXT;
BEGIN
    v_cleaned_author := TRIM(COALESCE(p_new_author_label, ''));
    IF v_cleaned_author = '' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Autor não pode ser vazio');
    END IF;

    -- 1. Verifica autorização: ESTRITAMENTE ADMIN (tokens e outros papéis NÃO podem corrigir autor)
    IF public.is_admin() THEN
        v_valid := true;
    ELSIF auth.uid() IS NOT NULL THEN
        SELECT EXISTS (
            SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
        ) INTO v_valid;
    END IF;

    IF NOT v_valid THEN
        RAISE EXCEPTION 'unauthorized: apenas administradores podem editar ou corrigir o autor do historico' USING ERRCODE = '28000';
    END IF;

    -- 2. Se foi passado history_id, atualiza no histórico
    IF p_history_id IS NOT NULL AND p_history_id > 0 THEN
        UPDATE public.publisher_profile_history
           SET author_label = v_cleaned_author
         WHERE id = p_history_id
        RETURNING publisher_id INTO v_publisher_id;
    END IF;

    -- Se v_publisher_id ainda for nulo e tiver sido passado p_publisher_id
    IF v_publisher_id IS NULL AND p_publisher_id IS NOT NULL THEN
        v_publisher_id := p_publisher_id;
    END IF;

    -- 3. Atualiza também no profileMeta da tabela publishers
    IF v_publisher_id IS NOT NULL THEN
        UPDATE public.publishers
           SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{profileMeta,updatedBy}', to_jsonb(v_cleaned_author), false)
         WHERE id = v_publisher_id
           AND data ? 'profileMeta';
    END IF;

    RETURN jsonb_build_object(
        'success', true, 
        'publisher_id', v_publisher_id, 
        'history_id', p_history_id, 
        'new_author_label', v_cleaned_author
    );
END;
$function$;
